# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink:           pretty

remote_theme: pages-themes/time-machine@v0.2.0

# Setup
url:                 http://biscuit-archive.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:             # http://biscuit-foundation.github.io

title:               The Biscuit Archive ğŸª

# Pagination
paginate:            5
paginate_path:       '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  We preserve the thoughts of Biscuit.
# The tags listed as entries in the sidebar
sidebar_tags:        [essay]

# Fallback image and color if not overwritten for tag or post
image:               /public/img/001.jpg
color:               '#A85641'

# Fonts
font:                'Ubuntu Mono, consolas, å¾®è½¯é›…é»‘'
font_accent:         'Ubuntu Mono, consolas, åæ–‡ç»†é»‘, å¾®è½¯é›…é»‘'
load_google_fonts:   'consolas'

# About yourself
author:
  name:              'Trashcan Foundation'
  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
    

  social:
    github:          trashcan-foundation      

markdown: kramdown


compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [local]

sass:
  style:             compressed